#!/bin/bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2181

set -e 
set -o pipefail

bold="\033[1m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
normal="\033[0m"

PEPEPATH="$(dirname "$(readlink "$0")")"
COMMANDSPATH="$PEPEPATH/commands"
COMMAND=$1
PEPEURL="https://raw.githubusercontent.com/LeaveAirykson/Pepe/refs/heads/master/pepe"
VERSION="1.2.3"

function showhelp() {
    echo -e "${yellow}Usage${normal}"
    echo "pepe [COMMAND] [[OPTIONS]...]"
    echo ""
    echo -e "${yellow}Available commands${normal}"

    echo -e "${bold}version${normal}\nShow current version\n"
    echo -e "${bold}create${normal} [command]\nHelps creating custom commands\n"

    if [ -d "$COMMANDSPATH" ] && [ "$(ls -A "$COMMANDSPATH")" ]; then
        for file in "$COMMANDSPATH"/*; do
            filename="$(basename "$file")"
            descline="$(grep "\@desc" "$file" | head -n1)"
            optionline="$(grep "\@option" "$file" | head -n1)"
            desc="${descline/\# \@desc /}"
            optiondesc="${optionline/\# \@option /}"

            echo -e "${bold}$filename${normal} $optiondesc\n$desc\n"
        done
    fi
}

function create-command() {
    echo -e "\n${bold}Create custom command${normal}"

    if  [[ -z "$2" ]] ; then
        read -rep "Name of the command (no whitespace): " COMMANDNAME
    else
        COMMANDNAME=$2
    fi

    if [[ -n "$COMMANDNAME" ]] ; then
        if [ -f "$COMMANDSPATH/$COMMANDNAME" ]; then
            ERROR=true
            MESSAGE="A command with this name already exist!"
        else

            read -rep "Description: " DESCRIPTION
            read -rep "Usage: pepe $COMMANDNAME " OPTIONS

            touch "$COMMANDSPATH/$COMMANDNAME"
            {
                echo "#!/bin/bash"
                echo -e "# @desc $DESCRIPTION"

                if [[ -n "$OPTIONS" ]]; then
                    echo -e "# @option $OPTIONS"
                fi

                echo -e "# start your logic here"
                
            } >> "$COMMANDSPATH/$COMMANDNAME"

            chmod +x "$COMMANDSPATH/$COMMANDNAME"

            if [ $? -eq 0 ]; then
                MESSAGE="Success in creating $COMMANDSPATH/$COMMANDNAME."

            else
                ERROR=true
                MESSAGE="Error occured while trying to create custom config file."
            fi
        fi
    fi
}

function install() {
    if [ -d "$HOME/pepe" ]; then
        echo -e "pepe seems to be already installed. If you want to update run: pepe update".
        exit 0
    fi

    mkdir -vp "$HOME/pepe/commands"
    cp -v pepe "$HOME/pepe/pepe"
    ln -svf "$HOME/pepe/pepe" "$HOME/bin/pepe"

    echo -e "\npepe successfully installed!"
}

function uninstall() {
    rm -v "$HOME/bin/pepe"
    rm -rvf "$HOME/pepe"

    echo -e "\npepe successfully uninstalled!"
}

function update() {
    wget -q --show-progress -O "$HOME/pepe/pepe" "$PEPEURL"
    chmod a+x "$HOME/pepe/pepe"

    echo -e "\npepe successfully updated!"
}


case "$COMMAND" in
    version|-v|v|--v)
        echo "$VERSION"
        ;;
    create|c)
        create-command "$@"
        ;;
    install)
        install
        ;;
    update)
        update
        ;;
    uninstall)
        uninstall
        ;;
    *)
        if [ -f "$COMMANDSPATH/$COMMAND" ]; then
            "$COMMANDSPATH/$COMMAND" "${@:2}"
        else
            showhelp
        fi
        ;;
esac